# Development version with hot reload
services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: stock_mysql_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: stock_management
      MYSQL_USER: stock_user
      MYSQL_PASSWORD: stock_password
    volumes:
      - mysql_dev_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - stock_network_dev

  # Laravel API Backend (Development)
  api-dev:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: stock_api_dev
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YourAppKeyHere
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=stock_management
      - DB_USERNAME=stock_user
      - DB_PASSWORD=stock_password
      - JWT_SECRET=your_jwt_secret_key_here
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./api:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - stock_network_dev
    command: php artisan serve --host=0.0.0.0 --port=8000

  # Next.js Frontend (Development)
  apps-dev:
    image: node:18-alpine
    container_name: stock_app_dev
    restart: unless-stopped
    working_dir: /app
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      - ./apps:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api-dev
    networks:
      - stock_network_dev
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_dev_data:
    driver: local

networks:
  stock_network_dev:
    driver: bridge